  name: 'GitHub Event Object Parser'
  description: 'Attempts to translate GHs event object into a human readable message'
  inputs:
    job-status:
      description: 'Define the status of the job'
      required: true
    run-id:
        description: 'Identifier for the current execution'
        required: true
  outputs:
    blocks:
      description: 'Human readable message with PR result'
  runs:
    using: 'node12'
    main: 'index.js'
