  name: 'GitHub Event Object Parser'
  description: 'Attempts to translate GHs event object into a human readable message'
  inputs:
    job-status:
      description: 'Define the status of the job'
      required: true
  outputs:
    message:
      description: 'Human readable message'
  runs:
    using: 'node12'
    main: 'index.js'
